CPP = g++
.SUFFIXES: .o .cpp
.cpp.o:
	$(CPP) $<

all: YourPets1 YourPets2 Run1 Run2

Run1:
	./YourPets1
Run2:
	./YourPets2
#yourpets1: YourPets1.cpp
#	$(CPP) YourPets1.cpp -o yourpets1

#yourpets2: YourPets2.cpp
#	$(CPP) YourPets2.cpp -o yourpets2 
